const colors = {
  light: {
    text: '#0A0F2E',
    tint: '#3D5EFC',
    background: '#F4F6FF',
    foreground: '#0A0F2E',
    card: '#FFFFFF',
    cardForeground: '#0A0F2E',
    primary: '#3D5EFC',
    primaryForeground: '#FFFFFF',
    secondary: '#EEF0FF',
    secondaryForeground: '#1A2060',
    muted: '#EEF0FF',
    mutedForeground: '#6B75A8',
    accent: '#3D5EFC',
    accentForeground: '#FFFFFF',
    destructive: '#FF4D70',
    destructiveForeground: '#FFFFFF',
    border: '#DDE1FF',
    input: '#E8EAFF',
    surface: '#F9FAFF',
    userBubble: '#3D5EFC',
    userBubbleForeground: '#FFFFFF',
    aiBubble: '#EEF0FF',
    aiBubbleForeground: '#0A0F2E',
    inputBg: '#FFFFFF',
    headerBg: '#FFFFFF',
    searchBg: '#EEF0FF',
    divider: '#E4E6FF',
  },
  dark: {
    text: '#EEF1FF',
    tint: '#5C7EFF',
    background: '#080910',
    foreground: '#EEF1FF',
    card: '#12132A',
    cardForeground: '#EEF1FF',
    primary: '#5C7EFF',
    primaryForeground: '#FFFFFF',
    secondary: '#181A30',
    secondaryForeground: '#C4CBFF',
    muted: '#181A30',
    mutedForeground: '#6673A0',
    accent: '#00D4FF',
    accentForeground: '#080910',
    destructive: '#FF4D70',
    destructiveForeground: '#FFFFFF',
    border: '#1E2244',
    input: '#0C0D1F',
    surface: '#0F1020',
    userBubble: '#1A2D7A',
    userBubbleForeground: '#EEF1FF',
    aiBubble: '#12132A',
    aiBubbleForeground: '#EEF1FF',
    inputBg: '#0C0D1F',
    headerBg: '#080910',
    searchBg: '#12132A',
    divider: '#1A1C32',
  },
  radius: 18,
};

export default colors;
